plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
      "@storybook/mdx2-csf": "*"
  "@storybook/mdx2-csf@*":
    dependencies:
      "@babel/types": "*"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
