name: ci-action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - develop

jobs:
  lint-and-test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: checkout action
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: file changes action
        uses: trilom/file-changes-action@master

      - name: save variable output files
        run: |
          echo "OUTPUT_FILES=$(cat $HOME/files.json)" >> $GITHUB_OUTPUT
        id: files

      - name: save target files
        run: |
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"service"* ]]; then
            echo "service=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"admin"* ]]; then
            echo "admin=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"hooks"* ]]; then
            echo "hooks=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.files.outputs.OUTPUT_FILES }}" == *"design-system"* ]]; then
            echo "design-system=true" >> $GITHUB_OUTPUT
          fi
        id: changes

      - name: yarn install
        run: yarn

      - name: run service eslint
        if: ${{ steps.changes.outputs.service == 'true' }}
        run: |
          yarn service:lint
          echo ${{ steps.changes.outputs.service == 'true' }}

      - name: run admin eslint
        if: ${{ steps.changes.outputs.admin == 'true' }}
        run: yarn admin:lint

      - name: run hooks eslint
        if: ${{ steps.changes.outputs.hooks == 'true' }}
        run: yarn hooks:lint

      - name: run design-system eslint
        if: ${{ steps.changes.outputs.design-system == 'true' }}
        run: yarn design-system:lint
